name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.4']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, log_errors=1
          coverage: pcov
          tools: pecl
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run PHPUnit
        env:
          EXT_IP_KEY: ${{ secrets.EXT_IP_KEY }}
        run: php vendor/bin/phpunit ./tests --coverage-text --whitelist ./src